#
# SPDX-FileCopyrightText: Copyright 2020, 2022 Andreas Sandberg <andreas@sandberg.uk>
#
# SPDX-License-Identifier: 0BSD
#

---
name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.16.x', '^1.x']

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v -mod=readonly ./...

      - name: test
        run: go test -v ./...
