#
# SPDX-FileCopyrightText: Copyright 2022 Andreas Sandberg <andreas@sandberg.uk>
#
# SPDX-License-Identifier: 0BSD
#

---
name: REUSE

on: [push, pull_request]

jobs:
  license:
    name: License checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: REUSE Compliance check
        uses: fsfe/reuse-action@v1.1.1
